---
title: "DATS6101_Summary_Report"
author: "Team 5"
date: "2024-11-01"
output: html_document
---

# Abstract 

# 1. Introduction
- Background
- Objectives
- Initial researh questions (areas of interest eg. temporal....)
- How did the research you gathered contribute to your question development?


# 2. Dataset Overview
- what do we know about the data set?
- how was the information gathered?

# 3. Data Preprocessing


# 4. Analyses and Results

## 4.1 Temporal Analysis
### 4.1.1 Exploratory Data Analysis (EDA)

### 4.1.2 Research Question/Hypothesi Development
- How did your question change, if at all, after Exploratory Data Analysis? 
- Based on EDA can you begin to sketch out an answer to your question?

### 4.1.3 Statistical Tests

### 4.1.4 Insights


## 4.2 Environmental Analysis
### 4.2.1 Exploratory Data Analysis (EDA)

### 4.2.2 Research Question/Hypothesi Development
- How did your question change, if at all, after Exploratory Data Analysis? 
- Based on EDA can you begin to sketch out an answer to your question?

### 4.2.3 Statistical Tests

### 4.2.4 Insights


# Conclusion
## Overall Summary and Key Findings
## Limitations and Directions for Future Research
- What are the limitations of the dataset?
- What additional information would be beneficial?

# References
# Appendix
